steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/microservicios-nest/image-registry/client-gateway",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/microservicios-nest/image-registry/client-gateway",
      ]
options:
  logging: CLOUD_LOGGING_ONLY